using RevitLookup.Abstractions.Enums.AboutProgram;

namespace RevitLookup.UI.Framework.Converters.ValueConverters;

public sealed class SoftwareUpdateStateCollapsedVisibilityConverter : EnumCollapsedVisibilityConverter<SoftwareUpdateState>;